export const ADD_ARTICLE = "ADD_ARTICLE";
export const SAVE_ARTICLE = "SAVE_ARTICLE";

export const FETCH_ARTICLES_PENDING = 'FETCH_ARTICLES_PENDING';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR   = 'FETCH_ARTICLES_ERROR';
